### ISSUE TITLE
Output before header function is called

### ISSUE THREAD

**Issue by rapphil** [shirosaidev/diskover-web#1]
I found an issue while using diskover-web. After I select an index, and click in the submit button, the pages is not redirect and an warning message is presented:
```Warning: Cannot modify header information - headers already sent by ```
It happens that this issue was being cause because there was output before the header function is called:
https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

There output being generated in the selectindices.php file before this line.
https://github.com/shirosaidev/diskover-web/blob/master/public/selectindices.php#L70

**Comment by shirosaidev** [comment]
this has been patched now, closing.
