### ISSUE TITLE
REST API: How is it supposed to work?

### ISSUE THREAD

**Issue by helge000** [shirosaidev/diskover-web#10]
Using `curl` with the given examples, I only manage to get:

```json
{
    "version": "diskover REST API v1",
    "message": "endpoint not found"
}
```

Secondly, how is the API supposed to work when I tuned on authentication?

Thanks,

**Comment by shirosaidev** [comment]
What are the full commands you are using with curl?
Authentication in elasticsearch or in diskover-web?

**Comment by shirosaidev** [comment]
I've pushed an update to rc16 which has a fix for using curl with the api.
The api does not use diskover-web auth, so will ignore login if you are using that in diskover-web.

**Comment by shirosaidev** [comment]
@helge000 is this working for you now?

**Comment by helge000** [comment]
@shirosaidev , sorry for the delay. I updated to `v1.5.0-rc19`, and now it seems to work!
