### ISSUE TITLE
api: list indices

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover-web#12]
is there a way to list all indices via the API?

**Comment by shirosaidev** [comment]
You can't do it from diskover-web api, but you can get it from es api
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_list_all_indices.html
This should grab all the diskover indices
curl -X GET "localhost:9200/_cat/indices?v&index=diskover-*"

**Comment by mathse** [comment]
> You can't do it from diskover-web api, but you can get it from es api
> https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_list_all_indices.html
> This should grab all the diskover indices
> curl -X GET "localhost:9200/_cat/indices?v&index=diskover-*"

yes - but in this case I don't need the diskover-web api for anything ...


a diskover-web api list function could also list the main stats like dir count, file count, dupes etc

**Comment by shirosaidev** [comment]
I'll mark this as enhancement for feature request.
so you'd like to see a diskover-web api call to return all the diskover indices with some stats for each index? Anything else?

**Comment by mathse** [comment]
Nope that's all I would like to have.

- -

Sent from Nine
________________________________

**Comment by shirosaidev** [comment]
list endpoint added to api in v1.5.0-rc25
