### ISSUE TITLE
Running On Apache

### ISSUE THREAD

**Issue by tashbocker** [shirosaidev/diskover-web#19]
Can i get some general guidance on how best to setup diskover-web? As recommended im trying to avoid using the php test method (Which works so i know that elasticsearch is running). I have tried both Apache and nginx. I get a login page asking for credentials but get  the following error in the Apache logs after login:

PHP Fatal error:  Uncaught Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException: No alive nodes found in your cluster in /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51\nStack trace:\n#0 /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(72): Elasticsearch\\ConnectionPool\\StaticNoPingConnectionPool->nextConnection()\n#1 /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(90): Elasticsearch\\Transport->getConnection()\n#2 /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(240): Elasticsearch\\Transport->performRequest('HEAD', '', Array, NULL, Array)\n#3 /var/www/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array)\n#4 /var/www/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n#5 /var/www/vendor/guzzlehttp/ri in /var/www/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51

**Comment by shirosaidev** [comment]
Did you set the variables in Constants.php (diskover-web config file) for your es host ip/hostname and port, etc ?
https://github.com/shirosaidev/diskover-web/wiki/Getting-Started

**Comment by tashbocker** [comment]
Yes I have they are running on the same server. Im attempting to run this on RedHat. Is composer whats used for PHP to be able to query ElasticSearch? Im wondering if this is where things are breaking.
