### ISSUE TITLE
Request: support multiple tags per file, directory

### ISSUE THREAD

**Issue by cazador481** [shirosaidev/diskover-web#20]
I would like to be able to set multiple tags on a file, or a directory.  When I try add a second tag to a file, the original one gets displaced.  I used the diskover webpage to add the tags by modifying the tag of a search.

**Comment by shirosaidev** [comment]
fyi, to update everyone about this, multi custom tag support is being worked on by me... hopefully released in September sometime in new diskover es7 ver...

**Comment by shirosaidev** [comment]
multiple custom tags is included in the enterprise version of diskover

**Comment by Sperryfreak01** [comment]
Awesome but not really something I would pay 6k/yr for.

edit:  That sounds like a dick comment and it probably was.  This is a great project thanks.
