### ISSUE TITLE
Overlay glitches

### ISSUE THREAD

**Issue by tronyx** [shirosaidev/diskover-web#21]
Noticed some glitches with the information overlay when viewing the heatmap and when trying to work with the drop-down menu for reindexing directories:

Heatmap: https://chrisyocum.com/Images/ShareX/2019-07-15_21-25-09.gif

Reindexing: https://chrisyocum.com/Images/ShareX/2019-07-15_21-26-28.gif

**Comment by shirosaidev** [comment]
this has been fixed in v1.5.0.3 latest release

**Comment by tronyx** [comment]
Everything looks good now, will close this.
