### ISSUE TITLE
Time Change Analytics Broken

### ISSUE THREAD

**Issue by Torqu3Wr3nch** [shirosaidev/diskover-web#22]
Spoke with shirosai on the LinuxServer.io discord server and he asked me to open this as he was also able to reproduce the issue.

The "Time Change" analytics section is totally broken. When I restart the container, I am able to at least load the "Time Change" page but the graphs are all empty. When I change the filter (to mtime=1 day), I get a 500 error when I reload "Time Change".

**Comment by shirosaidev** [comment]
@Torqu3Wr3nch this has been fixed in v1.5.0.4 diskover-web

**Comment by Torqu3Wr3nch** [comment]
Fix confirmed. Thank you for the quick turnaround!
