### ISSUE TITLE
run in virtualhost

### ISSUE THREAD

**Issue by renarios** [shirosaidev/diskover-web#24]
Hi, when I run diskover-web with php -S <ip>:8000 the dashboard works fine, but when I run it in a virtualhost, it gives all kind of errors, like:
`00, 'query' => [ 'match' => [ 'state' => 'running' ] ] ]; $queryResponse = $client->search($searchParams); $totalcrawls = $queryRespo...`

Here's my virtualhost: 

```
<VirtualHost *:8000>
  DocumentRoot /usr/share/diskover-web/public
  ErrorLog ${APACHE_LOG_DIR}/error-diskover-web.log
  CustomLog ${APACHE_LOG_DIR}/access-diskover-web.log combined
  DirectoryIndex index.php

  alias /src "/usr/share/diskover-web/src"
  alias /vendor "/usr/share/diskover-web/vendor"

  <Directory "/usr/share/diskover-web/public/">
        Options +Indexes +FollowSymLinks +MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
  </Directory>
  <Directory "/usr/share/diskover-web/src/">
        Options +Indexes +FollowSymLinks +MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
  </Directory>
  <Directory "/usr/share/diskover-web/vendor/">
        Options +Indexes +FollowSymLinks +MultiViews
        AllowOverride None
        Order allow,deny
        allow from all
  </Directory>
</VirtualHost>
```
What can I do to make diskover-web work in apache2?

Cheers,
Rene

**Comment by shirosaidev** [comment]
what errors in apache logs are you seeing? Is php7 and php-fpm (fastcgi) set up correct for apache?

**Comment by damburgey** [comment]
Is that running inside your main httpd.conf?
Might be easier to just check your httpd.conf file has 
```
# Supplemental configuration
#
# Load config files in the "/etc/httpd/conf.d" directory, if any.
IncludeOptional conf.d/*.conf
```
And if so, create a diskover-web.conf file in /etc/httpd/conf/
with something simple for testing like:
```
Listen 8000
<VirtualHost *:8000>
        ServerName diskover-web
        ServerAlias diskover-web
        DocumentRoot "/path/to/diskover-web/public"
</VirtualHost>
```

If its file permission related, add your user to the apache group
Change ownership recursively of everything in your /path/to/diskover-web/public folder
Also make sure the apache group has access to all required files in /path/to/diskover-web/public
```
sudo usermod -a -G apache <yourusername>
sudo chown -R <yourusername>:apache /path/to/diskover-web/public
sudo chmod 2775 /path/to/diskover-web/public && find /path/to/diskover-web/public -type d -exec sudo chmod 2775 {} \;
find /path/to/diskover-web/public -type f -exec sudo chmod 0664 {} \;
```

**Comment by renarios** [comment]
It turned out that libapache2-mod-php was not installed properly. Reinstalling this mod was the solution

Thanks for your support!
