### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by gameforce** [shirosaidev/diskover-web#3]
Getting too many redirects error when trying to access diskover-web from chrome

crawl is successful, index gets created, verified with kibana
using elasticsearch 5.6

not sure how to fix this

[root@app1 public]# php -S app1:8088
PHP 5.6.33 Development Server started at Thu Mar 15 17:16:23 2018
Listening on http://app1:8088
Document root is /opt/diskover-web/public
Press Ctrl-C to quit.
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60344 [302]: /
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60346 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60348 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60350 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60352 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60354 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60356 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60358 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60360 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60362 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60364 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60366 [302]: /selectindices.php
[Thu Mar 15 17:16:23 2018] 172.16.20.4:60368 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60370 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60372 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60374 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60376 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60378 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60380 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60382 [302]: /selectindices.php
[Thu Mar 15 17:16:24 2018] 172.16.20.4:60384 [302]: /selectindices.php

**Comment by shirosaidev** [comment]
I just patched this, was a bug in the Diskover.php page causing this.

**Comment by hyattdrew11** [comment]
I am receiving this error as well.

**Comment by shirosaidev** [comment]
just patched this in v1.5.0-rc4 of diskover-web, let me know if this fixes it for you. Also what browser and web server software are you running diskover-web with?
